name: 'Python Setup'

inputs:
  CH_URL:
    required: true
  CH_USER:
    required: true
  SSH_PRIVATE_KEY:
    required: true
  B2_APPLICATION_KEY_ID:
    required: true
  B2_APPLICATION_KEY:
    required: true

runs:
  using: "composite"
  steps:
    - name: Add remote host key to known_hosts
      shell: bash
      run: |
          mkdir ~/.ssh
          ssh-keyscan ${{ inputs.CH_URL }} >> ~/.ssh/known_hosts
      
    - name: Add SSH key
      shell: bash
      run: |
          echo "${{ inputs.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
  
    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Create .env file
      shell: bash
      run: |
        echo B2_APPLICATION_KEY_ID=${{ inputs.B2_APPLICATION_KEY_ID }} >> .env
        echo B2_APPLICATION_KEY=${{ inputs.B2_APPLICATION_KEY }} >> .env
        echo CH_USER=${{ inputs.CH_USER }} >> .env
        echo CH_URL=${{ inputs.CH_URL }} >> .env
        echo SSH_KEY_PATH=~/.ssh/private_key >> .env

    - name: Cache specific file
      uses: actions/cache@v3
      with:
        path: artifacts/BasicCompanyDataAsOneFile-2023-11-01.csv
        key: ${{ runner.os }}-file-${{ 'BasicCompanyDataAsOneFile-2023-11-01.csv' }}
