name: Run Python script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: companieshouse
        environment-file: environment.yaml
        python-version: 3.9
        auto-activate-base: false

    - name: Install dependencies
      run: |
        conda info
        conda list
        conda config --show
        python -m pip install --upgrade pip
        pip install b2sdk

    - name: Run script
      run: python script.py
