name: Companies

concurrency: 
  group: companies
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/python-setup
      with:
        CH_URL: ${{ secrets.CH_URL }}
        CH_USER: ${{ secrets.CH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
    - name: Run script
      run: python plan.py https://download.companieshouse.gov.uk/BasicCompanyDataAsOneFile-2023-11-01.zip
      id: plan
    - name: Upload artifact
      if: steps.plan.outputs.matrix != '[]'
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts
    outputs:
      matrix: ${{ steps.plan.outputs.matrix }}
      batch_size: ${{ steps.plan.outputs.batch_size }}
      file_name: ${{ steps.plan.outputs.file_name }}

  process:
    needs: plan
    if: needs.plan.outputs.matrix != '[]'
    strategy:
      matrix:
        offset: ${{ fromJson(needs.plan.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/python-setup
      with:
        CH_URL: ${{ secrets.CH_URL }}
        CH_USER: ${{ secrets.CH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifacts
    - name: Run script
      env:
        OFFSET: ${{ matrix.offset }}
        BATCH_SIZE: ${{ needs.plan.outputs.batch_size }}
      run: python process.py $OFFSET $BATCH_SIZE
  
  conclude:
    needs: [plan, process]
    if: needs.plan.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/python-setup
      with:
        CH_URL: ${{ secrets.CH_URL }}
        CH_USER: ${{ secrets.CH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
    - name: Run script
      env:
        FILE_NAME: ${{ needs.plan.outputs.file_name }}
      run: python conclude.py $FILE_NAME