name: Run Python script

concurrency: 
  group: my-workflow
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        offset: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    steps:
    - uses: actions/checkout@v2

    - name: Add remote host key to known_hosts
      run: |
          mkdir ~/.ssh
          ssh-keyscan ${{ secrets.CH_URL }} >> ~/.ssh/known_hosts
      
    - name: Add SSH key
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo B2_APPLICATION_KEY_ID=${{ secrets.B2_APPLICATION_KEY_ID }} >> .env
        echo B2_APPLICATION_KEY=${{ secrets.B2_APPLICATION_KEY }} >> .env
        echo CH_USER=${{ secrets.CH_USER }} >> .env
        echo CH_URL=${{ secrets.CH_URL }} >> .env
        echo SSH_KEY_PATH=~/.ssh/private_key >> .env

    - name: Cache specific file
      uses: actions/cache@v2
      with:
        path: BasicCompanyDataAsOneFile-2023-11-01.csv
        key: ${{ runner.os }}-file-${{ 'BasicCompanyDataAsOneFile-2023-11-01.csv' }}

    - name: Run script {{ matrix.offset }} of 20
      run: python script.py {{ matrix.offset }} 20
