name: Run Python script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9

    - name: Install dependencies
      run: |
        conda install --file requirements.yaml
        python -m pip install --upgrade pip
        pip install b2sdk

    - name: Run script
      run: python script.py
