name: Run jobs

concurrency: 
  group: my-workflow
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/python-setup
    - name: Run script
      run: python plan.py
      id: plan
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts
    outputs:
      matrix: ${{ steps.plan.outputs.matrix }}
      batch_size: ${{ steps.plan.outputs.batch_size }}
      file_name: ${{ steps.plan.outputs.file_name }}

  process:
    needs: plan
    strategy:
      matrix:
        offset: ${{ fromJson(needs.plan.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/python-setup
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifacts

    - name: Run script
      env:
        OFFSET: ${{ matrix.offset }}
        BATCH_SIZE: ${{ needs.plan.outputs.batch_size }}
      run: python script.py $OFFSET $BATCH_SIZE
  
  conclude:
    needs: [plan, process]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/python-setup
    - name: Run script
      env:
        FILE_NAME: ${{ needs.plan.outputs.file_name }}
      run: python conclude.py $FILE_NAME